added MetricsName to keep common metric names
racker/salus-common pull request #74
Opened 2020-09-09 14:57 UTC by shabd67

# Resolves

[SALUS-1008](https://jira.rax.io/browse/SALUS-1008)

# What

added MetricsName to keep common metric names

2020-09-09 16:23 UTC, itzg requested changes
With the pre-review of monitor management, it looks like you could also add commonly used tag keys (and even tag values), such as "operation" and "service". And then for "operation" there would be some common tag values like "create", "update", "delete".

2020-09-09 16:23 UTC, itzg commented on src/main/java/com/rackspace/salus/common/config/MetricsName.java
> +public interface MetricsName {
nit:
```suggestion
public interface MetricsNames {
```

2020-09-10 14:11 UTC, itzg submitted a review, later dismissed

2020-09-10 14:55 UTC, jjbuchan reviewed
Was there other discussion I missed around @itzg 's previous suggestion about adding constants for the operations?

2020-09-10 14:57 UTC, itzg commented
> Was there other discussion I missed around @itzg 's previous suggestion about adding constants for the operations?

Yeah, our comments kind of conflicted :) but I'm good with introducing an adjacent class to hold the names of tag keys and values. Like `MetricTags`?

2020-09-14 14:10 UTC, itzg requested changes
Just a nit

2020-09-14 14:10 UTC, itzg commented on src/main/java/com/rackspace/salus/common/config/MetricTagsValues.java
> +public interface MetricTagsValues {
```suggestion
public interface MetricTagValues {
```

2020-09-14 14:41 UTC, itzg approved these changes

2020-09-15 05:33 UTC, merged