Added exception handler for MethodArgumentNotValidException
racker/salus-common pull request #76
Opened 2020-09-22 16:39 UTC by rohitsngh27

# Resolves
https://jira.rax.io/browse/SALUS-730

# What
Handling of MethodArgumentNotValidException for inconsistent error messages.

# How to test
This can be tested via REST call

2020-09-22 21:54 UTC, jjbuchan reviewed
Can you add an example of the before and after errors to the PR description?

In addition to my one comment about tests, I do wonder if you're able to add any tests to our other services to help validate this new behavior?  It would be good to have something in place to ensure we don't accidentally break this functionality in future.

2020-09-22 21:54 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
> +    body.remove("errors");
Can you make sure this doesn't cause unwanted issues with test-task failures.  @shabd67 added an `errors` field in https://github.com/racker/salus-telemetry-api/pull/95 for certain scenarios.  

I think everything will be fine since IIRC those request return a "good" status rather than an error but ensuring we have test cases to confirm that would be good.  The ones in his PR may be enough to cover it but I'd like you to confirm.

2020-09-23 10:35 UTC, rohitsngh27 commented on src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
> +    body.remove("errors");
I have verified the test case mentioned in above working and they are working fine

2020-09-23 11:04 UTC, rohitsngh27 commented
> Can you add an example of the before and after errors to the PR description?
> 
> In addition to my one comment about tests, I do wonder if you're able to add any tests to our other services to help validate this new behavior? It would be good to have something in place to ensure we don't accidentally break this functionality in future.

There are test cases already in place for such scenario.

2020-09-23 15:21 UTC, itzg commented on src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
> +    body.remove("errors");
Why did `errors` need to be removed? Do you have any examples of what was showing up there?

2020-09-23 15:28 UTC, rohitsngh27 commented on src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
> +    body.remove("errors");
If **errors** is there it shows in the final response and creates a big json response like this:-
`
{
  "timestamp": "2020-09-23T15:26:51.968+00:00",
  "status": 400,
  "error": "Bad Request",
  "exception": "org.springframework.web.bind.MethodArgumentNotValidException",
  "message": "Validation failed for argument [0] in public com.rackspace.salus.monitor_management.web.model.ZoneDTO com.rackspace.salus.monitor_management.web.controller.ZoneApiController.create(com.rackspace.salus.monitor_management.web.model.ZoneCreatePublic) throws com.rackspace.salus.telemetry.errors.AlreadyExistsException: [Field error in object 'zoneCreatePublic' on field 'name': rejected value [invalid/zone]; codes [PublicZoneName.zoneCreatePublic.name,PublicZoneName.name,PublicZoneName.java.lang.String,PublicZoneName]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [zoneCreatePublic.name,name]; arguments []; default message [name]]; default message [zone name must be public]] ",
  "errors": [
    {
      "codes": [
        "PublicZoneName.zoneCreatePublic.name",
        "PublicZoneName.name",
        "PublicZoneName.java.lang.String",
        "PublicZoneName"
      ],
      "arguments": [
        {
          "codes": [
            "zoneCreatePublic.name",
            "name"
          ],
          "arguments": null,
          "defaultMessage": "name",
          "code": "name"
        }
      ],
      "defaultMessage": "zone name must be public",
      "objectName": "zoneCreatePublic",
      "field": "name",
      "rejectedValue": "invalid/zone",
      "bindingFailure": false,
      "code": "PublicZoneName"
    }
  ],
  "app": "salus-telemetry-monitor-management",
  "host": "MCP2AKMD6M",
  "traceId": "c5815563477219d6"
}
`

2020-09-23 16:27 UTC, itzg commented on src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
> +    body.remove("errors");
It's certainly ugly, but `errors` looks very useful for Minvera to programmatically interpret and present to the user rather than having to parse out the failed fields from the verbage in `message`. I would prefer to keep `errors`, but @jjbuchan @GeorgeJahad what do you think?

If anything it looks like `message` could use some strategic trimming, but similarly there's useful info in there (even if it's ugly).

2020-09-23 16:50 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
> +    body.remove("errors");
If `message` can be improved i think `errors` can be removed, but I'd let Faraji see how things look and choose whether it is useful to him or not.

For the `message` I really don't think that it includes the classpaths.  Can you look to see how the error can be returned in a more "user friendly" way.  I think its safe to assume that the `message` is something that could be output to a customer facing UI.  You may need to experiment with different validation annotations to see if the output of one looks better than the other.

2020-09-23 16:52 UTC, jjbuchan commented
> There are test cases already in place for such scenario.

I don't think that would be the case.  If we're changing the output of an error we must have to either create or modify test cases to reflect that change.  I haven't seen any PRs related to that?

e.g. `message` used to look like `"message": ""` but is now different.  If possible, we should create/modify test cases to validate the new message.

2020-09-23 19:41 UTC, itzg requested changes

2020-09-23 19:41 UTC, itzg commented on src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
> +    message.delete(message.length() - 2, message.length());
There's a handy [joining](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/Collectors.html#joining(java.lang.CharSequence)) collector that will avoid the need to manually append and trim the StringBuilder. I'm also providing a suggestion of a further trimmed down wording that should read pretty nicely for most validation messages.

```suggestion
    String message = "One or more field validations failed: " +
    e.getBindingResult().getFieldErrors().stream()
    .map(error -> error.getField() + " " + error.getDefaultMessage())
    .collect(Collectors.joining(", ");
```

Using the example from Slack it should produce:
```
One or more field validations failed: resourceId must match \"[A-Za-z0-9.:-]+\", presenceMonitoringEnabled must not be null
```

2020-09-24 10:51 UTC, rohitsngh27 commented on src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
> +    message.delete(message.length() - 2, message.length());
It is giving nice response but shouldn't we have a specific marker on request body field that is failing. 
For example:-
**One or more field validations failed: provider may not be empty, name zone name must be public** 
Here **name zone name must be public** is kind of looking weird or maybe i can change the default message in code to **must be public** only.
What's your thought on this?

2020-09-24 14:29 UTC, itzg commented on src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
> +    message.delete(message.length() - 2, message.length());
Yeah, I'm thinking cases where the wording becomes awkward it's because the validation message wasn't phrased correctly. So, yes, in this case the annotation should have said "must be public".

I guess that means it would be good if you could skim the validation annotations to make sure they start with "must" or "may" and tend not to mention the field.

2020-09-24 14:45 UTC, itzg commented on src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
> +    message.delete(message.length() - 2, message.length());
As for

> shouldn't we have a specific marker on request body field that is failing

that's good point. Maybe something simple like putting single quotes around the field name part.

2020-09-24 17:49 UTC, itzg commented on src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
> +            .map(error -> error.getField() + " " + error.getDefaultMessage())
@jjbuchan @GeorgeJahad , what were your thoughts about whether or not to emphasize the field name in the resulting message? Single quotes around the field name might be a subtle but helpful way to call that out.

2020-09-24 23:16 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
> +            .map(error -> error.getField() + " " + error.getDefaultMessage())
I think I prefer keeping this message simpler.  If it was only representing a single failure it would be good, but since it is all failures including the field and the message could become massive.

I'm leaning towards only specifying the field names in this and then faraji can pull out the `message`s from the `errors` list.  I feel like that would display the errors more cleanly to the customer than one massive string.

2020-09-25 16:56 UTC, itzg commented on src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
> +            .map(error -> error.getField() + " " + error.getDefaultMessage())
I think this is the change that would work
```suggestion
            .map(error -> error.getField())
```

2020-09-25 17:13 UTC, rohitsngh27 commented on src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
> +            .map(error -> error.getField() + " " + error.getDefaultMessage())
Does that mean I should remove the changes in PR:-
https://github.com/racker/salus-telemetry-etcd-adapter/pull/68/files
?

2020-09-25 17:18 UTC, itzg commented on src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
> +            .map(error -> error.getField() + " " + error.getDefaultMessage())
That change is still good

2020-09-25 17:25 UTC, itzg approved these changes
Wait for @jjbuchan 's re-review before merging.

2020-09-25 17:42 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
> +            .map(error -> error.getField() + " " + error.getDefaultMessage())
Yeah, we'd still expect that new error to turn up in `errors`, right?

2020-09-25 17:44 UTC, jjbuchan approved these changes

2020-09-25 17:48 UTC, rohitsngh27 commented on src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
> +            .map(error -> error.getField() + " " + error.getDefaultMessage())
Yes...`errors` is an array object, So it will have multiple errors coming.

2020-09-25 18:02 UTC, merged