Handled case for HttpMessageNotReadableException in IllegalStateException handler
racker/salus-common pull request #77
Opened 2020-09-29 12:03 UTC by rohitsngh27

# Resolves
https://jira.rax.io/browse/SALUS-827

# What
Handle case for HttpMessageNotReadableException in IllegalStateException handler

# How to test
This can be tested via REST call

#  Example

**Before**
![image](https://user-images.githubusercontent.com/13554835/94555461-3fd2a580-0279-11eb-84ca-9b64528ac616.png)

**After**
![image](https://user-images.githubusercontent.com/13554835/94555528-5547cf80-0279-11eb-906a-c976c60968e6.png)

2020-09-29 13:14 UTC, itzg approved these changes
Much nicer error message!

2020-09-29 17:35 UTC, jjbuchan reviewed
Is it possible to remove the `nested exception` part in an easy way (without parsing)?

The first part of the error is very helpful but I'd bet some customers would see the entire thing and be overwhelmed.

If it's not, I'm ok with this format.

2020-09-29 17:39 UTC, rohitsngh27 commented
> Is it possible to remove the `nested exception` part in an easy way (without parsing)?
> 
> The first part of the error is very helpful but I'd bet some customers would see the entire thing and be overwhelmed.
> 
> If it's not, I'm ok with this format.

If i do like this in handler :-
`
if (e.getCause().getCause() instanceof JsonParseException)
{
      return respondWith(request, HttpStatus.BAD_REQUEST, e.getCause().getCause().getMessage());
}
`
than it's possible to remove that extra bit and final response would be like this:-
![image](https://user-images.githubusercontent.com/13554835/94595516-92778600-02a8-11eb-88af-eed2480fbb54.png)

2020-09-29 17:41 UTC, jjbuchan commented
I think I like that better.  @itzg any opinions?

2020-09-29 18:43 UTC, itzg commented
Yeah, that definitely looks better and seems easy to implement.

2020-09-29 18:52 UTC, jjbuchan approved these changes

2020-09-29 18:57 UTC, itzg requested changes

2020-09-29 18:57 UTC, itzg commented on src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
> +    if (e.getCause().getCause() instanceof JsonParseException) {
Now that I see it coded out, I'd feel better if you also checked `instanceof` the first layer `e.getCause()`. There are **many** reasons IllegalStateException gets thrown and some might not even have a sub-cause.

2020-09-30 13:32 UTC, itzg approved these changes

2020-09-30 13:33 UTC, merged